version: '3.1'

secrets:
  db_password:
    file: ./db_pass.txt

services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: db-mysql
    secrets:
      - db_password
    environment:
      MYSQL_DATABASE: jerry
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ticker-datavolume:/var/lib/mysql
  web:
    build: .
    command: node index.js
    secrets:
      - db_password
    environment:
      DB_JERRY_HOST: mysql
      DB_JERRY_USER: root
      DB_JERRY_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 8090:8090
    depends_on:
      - mysql
volumes:
  ticker-datavolume:
